apiVersion: batch/v1
kind: Job
metadata:
  name: django-db-migrate
  namespace: restaurant-prod
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: sueesh144/party-den:latest
        command: ["python", "manage.py", "migrate"]
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: django-secrets
      restartPolicy: OnFailure
